### ISSUE TITLE
Missing Boxes

### ISSUE THREAD

**Issue by almulder** [RetroHursty69/es-theme-boxalloyred#1]
Hey I know you made this along time ago but I have loved the work, However I am missing a few. Could you make them? I have no skills.

Atomiswave
Sega NAOMI
NEO-GEO CD 
PCFX
Satellaview
Super Nintendo CD - MSU1

**Comment by RetroHursty69** [comment]
Hi. I have added the following folders and media to this theme: atomiswave, pcfx, satellaview, neocdz, snesmsu1, naomi. Enjoy, Hursty

**Comment by RetroHursty69** [comment]
Hi

Wow, that theme is so old and out of date, There is a bit of work involved making the boxes. I am leaving for a holiday today but will be back Monday.
I made the required round wheels just now, but the boxes will have to wait until I get back from holidays.

Cheers
Hursty
